Repository RedisAI/RedisAI, pull requests merged in 2020-04, with the labels that each got.

#317 Performance improvement on AI.TENSORSET when setting data with BLOB format
  src/redisai.c
  src/tensor.c
  src/tensor.h
  src/tensor_struct.h
  test/tests_common.py
  test/tests_pytorch.py
  test/tests_tensorflow.py
Labels: enhancement, performance

#321 Code refactoring, consistent error messages, and RedisAI_ModelRun_RedisCommand optimizations
  src/CMakeLists.txt
  src/backends/onnxruntime.c
  src/backends/tensorflow.c
  src/backends/tflite.c
  src/backends/torch.c
  src/err.c
  src/model.c
  src/redisai.c
  src/redisai.h
  src/script.c
  src/tensor.c
  src/tensor.h
  src/util/queue.c
  src/util/queue.h
  test/tests_common.py
  test/tests_onnx.py
  test/tests_pytorch.py
  test/tests_tensorflow.py
  test/tests_tflite.py
Labels: enhancement, performance

#325 Refactor batching mechanism, solve threading issue
  src/backends.c
  src/backends.h
  src/backends/onnxruntime.c
  src/backends/onnxruntime.h
  src/backends/tensorflow.c
  src/backends/tensorflow.h
  src/backends/tflite.c
  src/backends/tflite.h
  src/backends/torch.c
  src/backends/torch.h
  src/model.c
  src/model.h
  src/model_struct.h
  src/redisai.c
Labels: bug

#322 WIP - AI.DAGRUN, commands code refactoring and improvement
  .circleci/config.yml
  .gitignore
  src/CMakeLists.txt
  src/backends/tensorflow.c
  src/backends/util.c
  src/backends/util.h
  src/background_workers.c
  src/background_workers.h
  src/config.c
  src/config.h
  src/dag.c
  src/dag.h
  src/err.c
  src/err.h
  src/model.c
  src/model.h
  src/model_script_run_session.c
  src/model_script_run_session.h
  src/model_struct.h
  src/redisai.c
  src/redisai.h
  src/run_info.c
  src/run_info.h
  src/script.c
  src/script.h
  src/stats.c
  src/stats.h
  src/tensor.c
  src/tensor.h
  src/tensor_struct.h
  src/util/dict.c
  src/util/siphash.c.inc
  test/test_requirements.txt
  test/tests_dag.py
  test/tests_onnx.py
Labels: enhancement

#334 Add DAGRUNRO command
  src/redisai.c
  test/tests_dag.py
Labels: enhancement

#342 invalid memory accesses fixes and improvements
  .circleci/config.yml
  opt/Makefile
  src/background_workers.c
  src/background_workers.h
  src/err.c
  src/libtorch_c/torch_c.cpp
  src/model.c
  src/redisai.c
  src/run_info.c
  test/includes.py
  test/tests_common.py
  test/tests_dag.py
  test/tests_pytorch.py
  test/tests_tensorflow.py
  test/tests_tflite.py
Labels: bug
