Repository RedisAI/RedisAI, pull requests merged in 2020-12, with the labels that each got.

#530 Expose Redis/RedisAI main thread cpu usage via modules info
  src/redisai.c
  tests/flow/tests_common.py
Labels: performance

#540 Reuse memory in TENSORSET
  src/tensor.c
Labels: enhancement

#507 Add valgrind to CI
  .circleci/config.yml
  opt/Makefile
  opt/redis_valgrind.sup
  opt/system-setup.py
  tests/flow/tests.sh
  tests/flow/tests_dag.py
  tests/flow/valgrind.sh
Labels: Small

#545 Fix unsafe dag release upon error
  src/background_workers.c
  tests/flow/tests_onnx.py
Labels: bug
