Repository RedisAI/RedisAI, pull requests merged in 2020-08, with the labels that each got.

#438 Fixed flagged as "getkeys-api" during the registration ( AI.DAGRUN, AI.DAGRUN_RO, AI.MODELRUN, AI.SCRIPTRUN )
  .circleci/config.yml
  opt/Makefile
  src/dag.c
  src/dag.h
  src/model.c
  src/model.h
  src/redisai.c
  src/run_info.c
  src/script.c
  src/script.h
  src/util/dict.c
  src/util/siphash.c.inc
  test/includes.py
  test/tests.sh
  test/tests_dag.py
  test/tests_onnx.py
  test/tests_pytorch.py
  test/tests_sanitizer.py
  test/tests_tensorflow.py
  test/tests_tflite.py
Labels: bug

#439 Include per background thread cpu usage info on info modules output
  src/redisai.c
  test/tests_common.py
Labels: enhancement

#453 Fix broken links in docs
  docs/performance.md
Labels: documentation
